import {
  calculateWeaponAttacks,
  getMaxLevelForStars,
  calculateUpgradeGain
} from "./weapons.js";
import { rarities, tiers, weaponBaseAttackEquipped } from "@ts/types";
import { WEAPON_RARITY, WEAPON_TIER, HIGH_TIER_RARITIES } from "@ts/types/constants.js";
import { loadoutStore } from "@ts/store/loadout.store.js";
import {
  updateUpgradePriorityChain,
  updateWeaponUpgradeColors
} from "./weapon-priority-ui.js";
function generateWeaponLevelsHTML() {
  return `
        <!-- Sub-tab Navigation -->
        <div class="optimization-sub-tabs">
            <button id="weapon-levels-subtab-button" class="tab-button active" onclick="switchWeaponLevelsTab('weapons-grid')">Weapons Grid</button>
            <button id="weapon-levels-subtab-button" class="tab-button" onclick="switchWeaponLevelsTab('upgrade-priority')">Upgrade Priority</button>
        </div>

        <!-- Weapons Grid Sub-Tab -->
        <div id="weapon-levels-weapons-grid" class="weapon-levels-subtab active">
            <!-- Summary Stats -->
            <div class="wl-summary-stats">
                <div class="wl-summary-card">
                    <span class="wl-summary-label">Total Inventory Attack %</span>
                    <div class="wl-summary-value" id="total-inventory-attack">0%</div>
                </div>
                <div class="wl-summary-card">
                    <span class="wl-summary-label">Equipped Attack %</span>
                    <div class="wl-summary-value" id="equipped-weapon-attack-pct">0%</div>
                </div>
                <div class="wl-summary-card">
                    <span class="wl-summary-label">Total Weapon Attack %</span>
                    <div class="wl-summary-value" id="total-weapon-attack">0%</div>
                </div>
            </div>

            <!-- Info Banner -->
            <div class="wl-info-banner">
                <div class="wl-info-banner-content">
                    <strong>Instructions:</strong> Click stars to set star rating, enter weapon level. Check the "E" button to equip a weapon. The given inventory attack gain % is how much you'd expect if you spent 10k shards on the given weapon.
                </div>
            </div>

            <!-- No Weapon Equipped Indicator -->
            <div id="no-weapon-equipped-indicator" class="wl-warning-banner">
                <span class="wl-warning-banner-icon">\u26A0\uFE0F</span>
                <span class="wl-warning-banner-text">No Weapon Equipped - Check the "E" button on a weapon to equip it</span>
            </div>

            <div id="weapons-grid">
                <!-- Weapons will be generated by initializeWeaponsUI() -->
            </div>
        </div>

        <!-- Upgrade Priority Sub-Tab -->
        <div id="weapon-levels-upgrade-priority" class="weapon-levels-subtab" style="display: none;">
            <!-- Content populated by weapon-priority-ui.ts -->
        </div>
    `;
}
window.setWeaponStars = setWeaponStars;
window.previewStars = previewStars;
window.resetStarPreview = resetStarPreview;
window.handleEquippedCheckboxChange = handleEquippedCheckboxChange;
window.handleWeaponLevelChange = handleWeaponLevelChange;
window.switchWeaponLevelsTab = switchWeaponLevelsTab;
window.updateWeaponBonuses = updateWeaponBonuses;
function initializeWeaponsUI() {
  const container = document.getElementById("setup-weapon-levels");
  if (container) {
    container.innerHTML = generateWeaponLevelsHTML();
  }
  const weaponsGrid = document.getElementById("weapons-grid");
  if (!weaponsGrid) return;
  let html = "";
  rarities.forEach((rarity) => {
    tiers.forEach((tier) => {
      const baseAtk = weaponBaseAttackEquipped[rarity]?.[tier];
      const rarityCapitalized = rarity.charAt(0).toUpperCase() + rarity.slice(1);
      const isDisabled = rarity === WEAPON_RARITY.ANCIENT && tier === WEAPON_TIER.T1;
      if (baseAtk === null || baseAtk === void 0 || isDisabled) {
        html += `<div class="weapon-card weapon-card--disabled" data-rarity="${rarity}">
                    <div class="weapon-header">${tier.toUpperCase()} ${rarityCapitalized}</div>
                    <div class="weapon-no-data">No data</div>
                </div>`;
      } else {
        const defaultStars = HIGH_TIER_RARITIES.includes(rarity) ? 1 : 5;
        html += `<div class="weapon-card" id="weapon-${rarity}-${tier}" data-rarity="${rarity}">
                    <!-- Equipped Checkbox in top right -->
                    <div class="weapon-equipped-toggle">
                        <input type="checkbox" id="equipped-checkbox-${rarity}-${tier}"
                               onchange="handleEquippedCheckboxChange('${rarity}', '${tier}')">
                        <label for="equipped-checkbox-${rarity}-${tier}"
                               class="weapon-equipped-label"
                               id="equipped-label-${rarity}-${tier}">E</label>
                    </div>

                    <div class="weapon-header">${tier.toUpperCase()} ${rarityCapitalized}</div>

                    <!-- Star Rating -->
                    <div class="weapon-stars">`;
        for (let i = 1; i <= 5; i++) {
          const activeClass = i <= defaultStars ? "active" : "";
          html += `<span class="star-individual ${activeClass}"
                                   onclick="setWeaponStars('${rarity}', '${tier}', ${i})"
                                   onmouseenter="previewStars('${rarity}', '${tier}', ${i})"
                                   onmouseleave="resetStarPreview('${rarity}', '${tier}')"
                                   id="star-${rarity}-${tier}-${i}">\u2B50</span>`;
        }
        html += `</div>
                    <input type="hidden" id="stars-${rarity}-${tier}" value="${defaultStars}">

                    <div class="weapon-input-group">
                        <label for="level-${rarity}-${tier}">Level</label>
                        <input type="number" min="0" max="200" class="weapon-input" id="level-${rarity}-${tier}"
                               placeholder="0-200" value="0" oninput="handleWeaponLevelChange('${rarity}', '${tier}')">
                    </div>

                    <div class="weapon-stats">
                        <span class="weapon-inventory-display" id="inventory-display-${rarity}-${tier}">0.0% inventory attack</span>
                    </div>

                    <div class="weapon-upgrade-efficiency" id="upgrade-gain-container-${rarity}-${tier}">
                        <span class="weapon-efficiency-text" id="upgrade-gain-${rarity}-${tier}"></span>
                    </div>

                    <div class="weapon-equipped-display" id="equipped-display-${rarity}-${tier}" style="display:none;">
                        <span class="weapon-equipped-value" id="equipped-value-${rarity}-${tier}">0.0% equipped attack</span>
                    </div>
                </div>`;
      }
    });
  });
  weaponsGrid.innerHTML = html;
}
function loadWeaponsUI() {
  const weapons = loadoutStore.getWeapons();
  Object.entries(weapons).forEach(([key, weapon]) => {
    const [rarity, tier] = key.split("-");
    const levelInput = document.getElementById(`level-${rarity}-${tier}`);
    if (levelInput) {
      levelInput.value = weapon.level.toString();
    }
    const starsInput = document.getElementById(`stars-${rarity}-${tier}`);
    if (starsInput) {
      starsInput.value = weapon.stars.toString();
      for (let i = 1; i <= 5; i++) {
        const starElem = document.getElementById(`star-${rarity}-${tier}-${i}`);
        if (starElem) {
          starElem.classList.toggle("active", i <= weapon.stars);
        }
      }
    }
    if (weapon.equipped) {
      setEquippedState(rarity, tier);
    }
    handleWeaponLevelChangeBulk(rarity, tier);
  });
  updateWeaponBonuses(false);
  updateWeaponUpgradeColors();
  updateEquippedWeaponIndicator();
}
function attachWeaponEventListeners() {
  initializeWeaponMaxLevels();
}
function initializeWeaponMaxLevels() {
  rarities.forEach((rarity) => {
    tiers.forEach((tier) => {
      const starsInput = document.getElementById(`stars-${rarity}-${tier}`);
      const levelInput = document.getElementById(`level-${rarity}-${tier}`);
      if (starsInput && levelInput) {
        const stars = parseInt(starsInput.value) || 5;
        const maxLevel = getMaxLevelForStars(stars);
        levelInput.setAttribute("max", maxLevel.toString());
      }
    });
  });
}
function setWeaponStars(rarity, tier, stars) {
  const starsInput = document.getElementById(`stars-${rarity}-${tier}`);
  if (!starsInput) return;
  const currentStars = parseInt(starsInput.value) || 0;
  const newStars = currentStars === stars ? 0 : stars;
  starsInput.value = newStars.toString();
  for (let i = 1; i <= 5; i++) {
    const starElem = document.getElementById(`star-${rarity}-${tier}-${i}`);
    if (starElem) {
      const isActive = i <= newStars;
      starElem.classList.toggle("active", isActive);
      if (isActive && i > currentStars) {
        starElem.classList.remove("pop");
        void starElem.offsetWidth;
        starElem.classList.add("pop");
      }
    }
  }
  handleWeaponLevelChange(rarity, tier);
  const key = `${rarity}-${tier}`;
  loadoutStore.updateWeapon(key, { stars: newStars });
}
function previewStars(rarity, tier, stars) {
  for (let i = 1; i <= 5; i++) {
    const starElem = document.getElementById(`star-${rarity}-${tier}-${i}`);
    if (starElem) {
      const shouldBeActive = i <= stars;
      starElem.style.opacity = shouldBeActive ? "1" : "0.25";
      starElem.style.filter = shouldBeActive ? "grayscale(0)" : "grayscale(0.7)";
      starElem.style.transform = shouldBeActive ? "scale(1)" : "scale(0.85)";
    }
  }
}
function resetStarPreview(rarity, tier) {
  const starsInput = document.getElementById(`stars-${rarity}-${tier}`);
  if (!starsInput) return;
  const currentStars = parseInt(starsInput.value) || 0;
  for (let i = 1; i <= 5; i++) {
    const starElem = document.getElementById(`star-${rarity}-${tier}-${i}`);
    if (starElem) {
      starElem.style.opacity = "";
      starElem.style.filter = "";
      starElem.style.transform = "";
    }
  }
}
function handleWeaponLevelChange(rarity, tier) {
  const levelInput = document.getElementById(`level-${rarity}-${tier}`);
  const starsInput = document.getElementById(`stars-${rarity}-${tier}`);
  if (!levelInput) return;
  const level = parseInt(levelInput.value) || 0;
  const stars = starsInput?.value !== void 0 && starsInput?.value !== "" ? parseInt(starsInput.value) : 5;
  const maxLevel = getMaxLevelForStars(stars);
  levelInput.setAttribute("max", maxLevel.toString());
  if (level > maxLevel) {
    levelInput.value = maxLevel.toString();
    return handleWeaponLevelChange(rarity, tier);
  }
  const { inventoryAttack, equippedAttack } = calculateWeaponAttacks(rarity, tier, level);
  const inventoryDisplay = document.getElementById(`inventory-display-${rarity}-${tier}`);
  if (inventoryDisplay) {
    inventoryDisplay.textContent = `${inventoryAttack.toFixed(1)}% inventory attack`;
  }
  const upgradeGainContainer = document.getElementById(`upgrade-gain-container-${rarity}-${tier}`);
  const upgradeGainDisplay = document.getElementById(`upgrade-gain-${rarity}-${tier}`);
  if (level < maxLevel && level > 0) {
    const equippedDisplay2 = document.getElementById(`equipped-display-${rarity}-${tier}`);
    const isEquipped = equippedDisplay2 && equippedDisplay2.style.display !== "none";
    const upgradeGain = calculateUpgradeGain(rarity, tier, level, stars, 1e3, isEquipped);
    if (upgradeGainDisplay && upgradeGain.attackGain > 0) {
      let gainPer1k;
      let totalGainPer1k;
      if (upgradeGain.isUnaffordable) {
        gainPer1k = upgradeGain.attackGain / upgradeGain.singleLevelCost * 1e3;
        const equippedGainPer1k = upgradeGain.equippedAttackGain / upgradeGain.singleLevelCost * 1e3;
        totalGainPer1k = gainPer1k + equippedGainPer1k;
        if (isEquipped) {
          upgradeGainDisplay.textContent = `+${totalGainPer1k.toFixed(2)}% per 1k shards (${gainPer1k.toFixed(2)}% inv + ${equippedGainPer1k.toFixed(2)}% eq, next level costs ${upgradeGain.singleLevelCost} shards)`;
        } else {
          upgradeGainDisplay.textContent = `+${gainPer1k.toFixed(2)}% per 1k shards (next level costs ${upgradeGain.singleLevelCost} shards)`;
        }
      } else {
        gainPer1k = upgradeGain.attackGain;
        totalGainPer1k = gainPer1k + upgradeGain.equippedAttackGain;
        if (isEquipped) {
          upgradeGainDisplay.textContent = `+${totalGainPer1k.toFixed(2)}% per 1k shards (${gainPer1k.toFixed(2)}% inv + ${upgradeGain.equippedAttackGain.toFixed(2)}% eq, ${upgradeGain.levelsGained} levels)`;
        } else {
          upgradeGainDisplay.textContent = `+${gainPer1k.toFixed(2)}% per 1k shards (${upgradeGain.levelsGained} levels)`;
        }
      }
      upgradeGainDisplay.dataset.gainPer1k = isEquipped ? totalGainPer1k.toString() : gainPer1k.toString();
      if (upgradeGainContainer) {
        upgradeGainContainer.classList.add("visible");
      }
    } else {
      if (upgradeGainContainer) {
        upgradeGainContainer.classList.remove("visible");
      }
    }
  } else {
    if (upgradeGainContainer) {
      upgradeGainContainer.classList.remove("visible");
    }
    if (upgradeGainDisplay) {
      delete upgradeGainDisplay.dataset.gainPer1k;
    }
  }
  const equippedDisplay = document.getElementById(`equipped-display-${rarity}-${tier}`);
  if (equippedDisplay && equippedDisplay.style.display !== "none") {
    const equippedValue = document.getElementById(`equipped-value-${rarity}-${tier}`);
    if (equippedValue) {
      equippedValue.textContent = `${equippedAttack.toFixed(1)}% equipped attack`;
    }
  }
  updateWeaponBonuses();
  updateEquippedWeaponIndicator();
  updateWeaponUpgradeColors();
  const key = `${rarity}-${tier}`;
  loadoutStore.updateWeapon(key, { level });
}
function handleWeaponLevelChangeBulk(rarity, tier) {
  const levelInput = document.getElementById(`level-${rarity}-${tier}`);
  const starsInput = document.getElementById(`stars-${rarity}-${tier}`);
  if (!levelInput) return;
  const level = parseInt(levelInput.value) || 0;
  const stars = starsInput?.value !== void 0 && starsInput?.value !== "" ? parseInt(starsInput.value) : 5;
  const maxLevel = getMaxLevelForStars(stars);
  levelInput.setAttribute("max", maxLevel.toString());
  if (level > maxLevel) {
    levelInput.value = maxLevel.toString();
    return handleWeaponLevelChangeBulk(rarity, tier);
  }
  const { inventoryAttack, equippedAttack } = calculateWeaponAttacks(rarity, tier, level);
  const inventoryDisplay = document.getElementById(`inventory-display-${rarity}-${tier}`);
  if (inventoryDisplay) {
    inventoryDisplay.textContent = `${inventoryAttack.toFixed(1)}% inventory attack`;
  }
  const upgradeGainContainer = document.getElementById(`upgrade-gain-container-${rarity}-${tier}`);
  const upgradeGainDisplay = document.getElementById(`upgrade-gain-${rarity}-${tier}`);
  if (level < maxLevel && level > 0) {
    const equippedDisplay2 = document.getElementById(`equipped-display-${rarity}-${tier}`);
    const isEquipped = equippedDisplay2 && equippedDisplay2.style.display !== "none";
    const upgradeGain = calculateUpgradeGain(rarity, tier, level, stars, 1e3, isEquipped);
    if (upgradeGainDisplay && upgradeGain.attackGain > 0) {
      let gainPer1k;
      let totalGainPer1k;
      if (upgradeGain.isUnaffordable) {
        gainPer1k = upgradeGain.attackGain / upgradeGain.singleLevelCost * 1e3;
        const equippedGainPer1k = upgradeGain.equippedAttackGain / upgradeGain.singleLevelCost * 1e3;
        totalGainPer1k = gainPer1k + equippedGainPer1k;
        if (isEquipped) {
          upgradeGainDisplay.textContent = `+${totalGainPer1k.toFixed(2)}% per 1k shards (${gainPer1k.toFixed(2)}% inv + ${equippedGainPer1k.toFixed(2)}% eq, next level costs ${upgradeGain.singleLevelCost} shards)`;
        } else {
          upgradeGainDisplay.textContent = `+${gainPer1k.toFixed(2)}% per 1k shards (next level costs ${upgradeGain.singleLevelCost} shards)`;
        }
      } else {
        gainPer1k = upgradeGain.attackGain;
        totalGainPer1k = gainPer1k + upgradeGain.equippedAttackGain;
        if (isEquipped) {
          upgradeGainDisplay.textContent = `+${totalGainPer1k.toFixed(2)}% per 1k shards (${gainPer1k.toFixed(2)}% inv + ${upgradeGain.equippedAttackGain.toFixed(2)}% eq, ${upgradeGain.levelsGained} levels)`;
        } else {
          upgradeGainDisplay.textContent = `+${gainPer1k.toFixed(2)}% per 1k shards (${upgradeGain.levelsGained} levels)`;
        }
      }
      upgradeGainDisplay.dataset.gainPer1k = isEquipped ? totalGainPer1k.toString() : gainPer1k.toString();
      if (upgradeGainContainer) {
        upgradeGainContainer.classList.add("visible");
      }
    } else {
      if (upgradeGainContainer) {
        upgradeGainContainer.classList.remove("visible");
      }
    }
  } else {
    if (upgradeGainContainer) {
      upgradeGainContainer.classList.remove("visible");
    }
    if (upgradeGainDisplay) {
      delete upgradeGainDisplay.dataset.gainPer1k;
    }
  }
  const equippedDisplay = document.getElementById(`equipped-display-${rarity}-${tier}`);
  if (equippedDisplay && equippedDisplay.style.display !== "none") {
    const equippedValue = document.getElementById(`equipped-value-${rarity}-${tier}`);
    if (equippedValue) {
      equippedValue.textContent = `${equippedAttack.toFixed(1)}% equipped attack`;
    }
  }
}
function refreshAllEquippedStates() {
  const weapons = loadoutStore.getWeapons();
  Object.entries(weapons).forEach(([key, weapon]) => {
    const [rarity, tier] = key.split("-");
    const checkbox = document.getElementById(`equipped-checkbox-${rarity}-${tier}`);
    const equippedDisplay = document.getElementById(`equipped-display-${rarity}-${tier}`);
    const card = document.getElementById(`weapon-${rarity}-${tier}`);
    if (!checkbox) return;
    checkbox.checked = weapon.equipped;
    if (weapon.equipped) {
      const levelInput = document.getElementById(`level-${rarity}-${tier}`);
      const level = parseInt(levelInput?.value) || 0;
      const { equippedAttack } = calculateWeaponAttacks(rarity, tier, level);
      const equippedValue = document.getElementById(`equipped-value-${rarity}-${tier}`);
      if (equippedValue) {
        equippedValue.textContent = `${equippedAttack.toFixed(1)}% equipped attack`;
      }
      if (equippedDisplay) equippedDisplay.style.display = "block";
      if (card) card.classList.add("equipped");
    } else {
      if (equippedDisplay) equippedDisplay.style.display = "none";
      if (card) card.classList.remove("equipped");
    }
  });
}
function handleEquippedCheckboxChange(rarity, tier) {
  const checkbox = document.getElementById(`equipped-checkbox-${rarity}-${tier}`);
  if (!checkbox) return;
  const key = `${rarity}-${tier}`;
  if (checkbox.checked) {
    const weapons = loadoutStore.getWeapons();
    Object.entries(weapons).forEach(([otherKey, otherWeapon]) => {
      if (otherKey !== key && otherWeapon.equipped) {
        loadoutStore.updateWeapon(otherKey, { equipped: false });
      }
    });
    loadoutStore.updateWeapon(key, { equipped: true });
  } else {
    loadoutStore.updateWeapon(key, { equipped: false });
  }
  refreshAllEquippedStates();
  updateWeaponBonuses();
  updateEquippedWeaponIndicator();
}
function setEquippedState(rarity, tier) {
  const checkbox = document.getElementById(`equipped-checkbox-${rarity}-${tier}`);
  const equippedDisplay = document.getElementById(`equipped-display-${rarity}-${tier}`);
  const card = document.getElementById(`weapon-${rarity}-${tier}`);
  if (!checkbox) return;
  checkbox.checked = true;
  rarities.forEach((r) => {
    tiers.forEach((t) => {
      if (r !== rarity || t !== tier) {
        const otherCheckbox = document.getElementById(`equipped-checkbox-${r}-${t}`);
        const otherDisplay = document.getElementById(`equipped-display-${r}-${t}`);
        const otherCard = document.getElementById(`weapon-${r}-${t}`);
        if (otherCheckbox) otherCheckbox.checked = false;
        if (otherDisplay) otherDisplay.style.display = "none";
        if (otherCard) otherCard.classList.remove("equipped");
      }
    });
  });
  const levelInput = document.getElementById(`level-${rarity}-${tier}`);
  const level = parseInt(levelInput?.value) || 0;
  const { equippedAttack } = calculateWeaponAttacks(rarity, tier, level);
  const equippedValue = document.getElementById(`equipped-value-${rarity}-${tier}`);
  if (equippedValue) {
    equippedValue.textContent = `${equippedAttack.toFixed(1)}% equipped attack`;
  }
  if (equippedDisplay) equippedDisplay.style.display = "block";
  if (card) card.classList.add("equipped");
}
function updateEquippedWeaponIndicator() {
  let hasEquipped = false;
  rarities.forEach((rarity) => {
    tiers.forEach((tier) => {
      const equippedDisplay = document.getElementById(`equipped-display-${rarity}-${tier}`);
      if (equippedDisplay && equippedDisplay.style.display !== "none") {
        hasEquipped = true;
      }
    });
  });
  const indicator = document.getElementById("no-weapon-equipped-indicator");
  if (indicator) {
    indicator.style.display = hasEquipped ? "none" : "block";
  }
}
function updateWeaponBonuses(calculateDamage = true) {
  let totalInventory = 0;
  let equippedBonus = 0;
  rarities.forEach((rarity) => {
    tiers.forEach((tier) => {
      const levelInput = document.getElementById(`level-${rarity}-${tier}`);
      const equippedDisplay = document.getElementById(`equipped-display-${rarity}-${tier}`);
      if (levelInput) {
        const level = parseInt(levelInput.value) || 0;
        const { inventoryAttack, equippedAttack } = calculateWeaponAttacks(rarity, tier, level);
        totalInventory += inventoryAttack;
        if (equippedDisplay && equippedDisplay.style.display !== "none") {
          equippedBonus = equippedAttack;
        }
      }
    });
  });
  const totalInventoryEl = document.getElementById("total-inventory-attack");
  const equippedEl = document.getElementById("equipped-weapon-attack-pct");
  const totalEl = document.getElementById("total-weapon-attack");
  if (totalInventoryEl) totalInventoryEl.textContent = totalInventory.toFixed(1) + "%";
  if (equippedEl) equippedEl.textContent = equippedBonus.toFixed(1) + "%";
  if (totalEl) totalEl.textContent = (totalInventory + equippedBonus).toFixed(1) + "%";
  loadoutStore.updateWeaponAttackBonus({
    totalAttack: totalInventory + equippedBonus,
    equippedAttack: equippedBonus
  });
  if (calculateDamage) {
  }
  updateUpgradePriorityChain();
}
function switchWeaponLevelsTab(tabName) {
  const allSubTabContent = document.querySelectorAll(".weapon-levels-subtab");
  const allSubTabButtons = document.querySelectorAll("#weapon-levels-subtab-button");
  allSubTabContent.forEach((tab) => {
    tab.classList.remove("active");
    tab.style.display = "none";
  });
  allSubTabButtons.forEach((btn) => {
    btn.classList.remove("active");
  });
  const selectedTab = document.getElementById(`weapon-levels-${tabName}`);
  if (selectedTab) {
    selectedTab.classList.add("active");
    selectedTab.style.display = "block";
  }
  allSubTabButtons.forEach((btn) => {
    const onclickAttr = btn.getAttribute("onclick");
    if (onclickAttr && onclickAttr.includes(tabName)) {
      btn.classList.add("active");
    }
  });
  if (tabName === "upgrade-priority") {
    setTimeout(() => {
      updateUpgradePriorityChain();
    }, 100);
  }
}
export {
  attachWeaponEventListeners,
  handleEquippedCheckboxChange,
  handleWeaponLevelChange,
  handleWeaponLevelChangeBulk,
  initializeWeaponsUI,
  loadWeaponsUI,
  previewStars,
  resetStarPreview,
  setEquippedState,
  setWeaponStars,
  switchWeaponLevelsTab,
  updateEquippedWeaponIndicator,
  updateUpgradePriorityChain,
  updateWeaponBonuses,
  updateWeaponUpgradeColors
};
//# sourceMappingURL=weapon-ui.js.map
