// Scrolling Analysis - Equipment Slot Performance & Scroll Simulation
// This module manages the scrolling optimizer tab functionality

import {
    runScrollSimulation,
    updateScrollLevelInfo,
    switchScrollStrategyTab
} from './scroll-optimizer.js';
import {
    initializeEquipmentSlots,
    loadEquipmentSlots,
} from '@ui/equipment-ui.js';
import { calculateEquipmentSlotDPS } from '@ui/results-display.js';

// Make functions available globally for onclick handlers
window.switchScrollingSubTab = switchScrollingSubTab;
window.runScrollSimulation = runScrollSimulation;
window.updateScrollLevelInfo = updateScrollLevelInfo;
window.switchScrollStrategyTab = switchScrollStrategyTab;
window.calculateEquipmentSlotDPS = calculateEquipmentSlotDPS;
window.updateGuildSkillDisplay = updateGuildSkillDisplay;

// Update Guild Skill display value
export function updateGuildSkillDisplay() {
    const slider = document.getElementById('scroll-guild-skill');
    const display = document.getElementById('guild-skill-value');
    if (slider && display) {
        const value = slider.value;
        display.textContent = value + '%';

        // Update styling based on value
        if (value > 0) {
            display.classList.add('boosted');
        } else {
            display.classList.remove('boosted');
        }

        // Update slider data attribute for CSS styling
        slider.setAttribute('data-value', value);

        // Update tick marks
        const ticks = document.querySelectorAll('.scrolling-guild__tick');
        ticks.forEach((tick, index) => {
            if (index <= parseInt(value)) {
                tick.classList.add('active');
            } else {
                tick.classList.remove('active');
            }
        });
    }
}

// Switch scrolling sub-tabs (mirrors inner-ability.js pattern)
export function switchScrollingSubTab(tabName) {
    const allSubTabContent = document.querySelectorAll('.scrolling-subtab'); 
    const allSubTabButtons = document.querySelectorAll('#scrolling-tab-button'); 

    // Hide all subtabs
    allSubTabContent.forEach(tab => {
        tab.classList.remove('active');
        tab.style.display = 'none';
    });
    
    // Remove active from all buttons - update to use new tab-button class
    allSubTabButtons.forEach(btn => {
        btn.classList.remove('active');
    });
    
    // Show selected subtab
    const selectedTab = document.getElementById(`scrolling-${tabName}`);
    if (selectedTab) {
        selectedTab.classList.add('active');
        selectedTab.style.display = 'block';
    }
    
    // Activate button - Find the button by matching the onclick attribute
    // This works both when called from a click event and during initialization    
    allSubTabButtons.forEach(btn => {
        const onclickAttr = btn.getAttribute('onclick');
        if (onclickAttr && onclickAttr.includes(`'${tabName}'`)) {
            btn.classList.add('active');
        }
    });
    
    // Render content
    if (tabName === 'my-slot-performance') {
        renderMySlotPerformance();
    } else if (tabName === 'simulation') {
        renderSimulation();
    }
}

// Render My Slot Performance tab
export function renderMySlotPerformance() {
    const container = document.getElementById('scrolling-my-slot-performance');
    if (!container) return;

    let html = `
        <div class="optimization-info-banner">
            <span class="optimization-info-banner-icon">ℹ️</span>
            <div style="color: var(--text-primary); font-size: 0.9em; line-height: 1.5;">
                <strong>Equipment Slot Analysis:</strong> Track individual equipment slot values in isolation. Each slot's DPS gain is calculated by comparing damage WITH that slot's stats vs damage WITH zero stats from that slot.
            </div>
        </div>
        <div id="equipment-slots-grid" class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <!-- Slot cards generated by JavaScript -->
        </div>
        <div style="margin-top: 20px; text-align: center;">
            <div style="background: linear-gradient(135deg, rgba(0, 122, 255, 0.15), rgba(88, 86, 214, 0.1)); border: 2px solid var(--accent-primary); border-radius: 12px; padding: 20px; max-width: 500px; margin: 0 auto 20px; box-shadow: 0 4px 16px var(--shadow);">
                <div style="color: var(--text-secondary); font-size: 0.9em; margin-bottom: 8px; font-weight: 500;">Total DPS Gain from All Slots</div>
                <div style="color: var(--accent-primary); font-size: 2em; font-weight: 700;">
                    <span id="total-slots-dps">0%</span>
                </div>
            </div>
            <button class="calculate-btn" onclick="calculateEquipmentSlotDPS()" style="max-width: 400px; margin: 0 auto;">Calculate Slot DPS</button>
        </div>
    `;

    container.innerHTML = html;

    // Initialize equipment slots after DOM is ready
    setTimeout(() => {
        initializeEquipmentSlots();
        loadEquipmentSlots();
    }, 0);
}

// Render Simulation tab
export function renderSimulation() {
    const container = document.getElementById('scrolling-simulation');
    if (!container) return;

    let html = `
        <div class="optimization-info-banner">
            <span class="optimization-info-banner-icon">⚡</span>
            <div style="color: var(--text-primary); font-size: 0.9em; line-height: 1.5;">
                <strong>Scroll Optimizer:</strong> Simulates different scrolling strategies using Level 65 scrolls to find the optimal approach. The damage gain shows how much your DPS will increase from the average scroll results.
            </div>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            <div class="input-group">
                <label>Spell Trace Budget</label>
                <input type="number" id="scroll-spell-trace-budget" value="7000" min="500" max="50000" step="100">
            </div>
            <div class="input-group">
                <label>Number of Simulations</label>
                <input type="number" id="scroll-simulations" value="500" min="100" max="10000" step="100">
            </div>
        </div>

        <div class="scrolling-enhancements">
            <div class="scrolling-enhancements__grid">
                <label class="scrolling-premium__label">
                    <input type="checkbox" id="scroll-premium-membership" class="scrolling-premium__checkbox" onchange="updateScrollLevelInfo()">
                    <span class="scrolling-premium__text">
                        Premium
                        <span class="scrolling-premium__badge">+2%</span>
                    </span>
                    <span class="scrolling-premium__sparkles">✨</span>
                </label>

                <div class="scrolling-guild">
                    <span class="scrolling-guild__icon">⚔️</span>
                    <span class="scrolling-guild__label">Guild Skill</span>
                    <div class="scrolling-guild__slider-container">
                        <input type="range" id="scroll-guild-skill" class="scrolling-guild__slider" min="0" max="3" step="1" value="0"
                               oninput="updateGuildSkillDisplay(); updateScrollLevelInfo();"
                               data-value="0">
                    </div>
                    <span id="guild-skill-value" class="scrolling-guild__value">0%</span>
                </div>
            </div>
        </div>

        <div style="background: rgba(0, 122, 255, 0.05); border: 1px solid var(--border-color); border-radius: 8px; padding: 15px; margin-bottom: 15px;">
            <label style="font-weight: 600; margin-bottom: 10px; display: block; color: var(--text-primary);">Scroll Level</label>
            <div style="display: flex; gap: 20px;">
                <label style="display: flex; align-items: center; cursor: pointer; font-size: 0.95em;">
                    <input type="radio" name="scroll-level" value="65" checked onchange="updateScrollLevelInfo()" style="margin-right: 8px; cursor: pointer;">
                    <span style="color: var(--text-primary);">Level 65 Scrolls</span>
                </label>
                <label style="display: flex; align-items: center; cursor: pointer; font-size: 0.95em;">
                    <input type="radio" name="scroll-level" value="85" onchange="updateScrollLevelInfo()" style="margin-right: 8px; cursor: pointer;">
                    <span style="color: var(--text-primary);">Level 85 Scrolls</span>
                </label>
            </div>
            <div id="scroll-level-info" style="margin-top: 12px; padding: 10px; background: var(--background); border-radius: 6px; font-size: 0.85em; color: var(--text-secondary); line-height: 1.6;">
                <!-- Info will be populated by JavaScript -->
            </div>
        </div>

        <button class="calculate-btn" onclick="runScrollSimulation()" id="scroll-run-btn">Run Simulation</button>

        <div id="scroll-progress-container" style="display: none; margin-top: 15px;">
            <div style="width: 100%; height: 4px; background: var(--border-color); border-radius: 2px; overflow: hidden;">
                <div id="scroll-progress-bar" style="height: 100%; background: var(--accent-primary); transition: width 0.3s; width: 0%;"></div>
            </div>
            <p id="scroll-progress-text" style="text-align: center; color: var(--text-secondary); margin-top: 8px;"></p>
        </div>

        <div id="scroll-results-container" style="margin-top: 20px;">
            <!-- Results will be populated by JavaScript -->
        </div>
    `;

    container.innerHTML = html;

    // Initialize scroll level info after DOM is ready
    setTimeout(() => {
        updateScrollLevelInfo();
    }, 0);
}

// Initialize Scrolling Analysis
export function initializeScrollingAnalysis() {
    renderMySlotPerformance();
    renderSimulation();
}
